#! /bin/sh

bspc config border_width        2
bspc config window_gap          30

bspc config split_ratio         0.52
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true

bspc monitor -d Game Web Steam Code Mail LE Cell
#bspc monitor HDMI-0 -d Mon2

bspc rule -a Steam desktop=^3 #fullscreen=on
bspc rule -a Atom desktop=^4
